/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:132716bf-42cc-42b8-b949-8b227941c02c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_OOg84TXTa",
    "aws_user_pools_web_client_id": "207vki3vsji9b6j9pnvat43ihf",
    "oauth": {}
};


export default awsmobile;
